name: Run JMeter Load Tests and Deploy Report to Main

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz -o jmeter.tgz
          tar -xzf jmeter.tgz
          mv apache-jmeter-5.6.3 jmeter
          echo "$GITHUB_WORKSPACE/jmeter/bin" >> $GITHUB_PATH

      - name: Run JMeter tests and generate report
        run: |
          mkdir -p result docs
          jmeter -n -t POST-cadastrado_usuario.jmx -l result/result.jtl -e -o docs
          touch docs/.nojekyll

      - name: Commit and push report to main branch
        run: |
          git config user.name "CristianoSFMothe"
          git config user.email "CristianoSFMothe@users.noreply.github.com"
          git add docs .nojekyll
          git commit -m "chore: update JMeter report"
          git push origin main
        env:
          # Usar token com permissão para push no main (por padrão GITHUB_TOKEN permite)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
